### ISSUE TITLE
width 200% causes slide of navigation to expand past window

### ISSUE THREAD

**Issue by JackHowa** [WPMedia/fusion-news-theme-blocks#701]
<img width="668" alt="Screen Shot 2021-01-22 at 16 16 44" src="https://user-images.githubusercontent.com/5950956/105554610-5049d880-5ccd-11eb-9c8e-b56c3dc69d1c.png">
<img width="1425" alt="Screen Shot 2021-01-22 at 16 15 56" src="https://user-images.githubusercontent.com/5950956/105554621-563fb980-5ccd-11eb-9ce1-5a87892ec704.png">
<img width="721" alt="Screen Shot 2021-01-22 at 16 16 20" src="https://user-images.githubusercontent.com/5950956/105554622-563fb980-5ccd-11eb-82b8-d293d9028e6a.png">

```scss
.nav-sections {
  background: rgba(25, 25, 25, 0);
  flex-direction: column;
  -ms-overflow-style: none;
  position: absolute;
  scrollbar-width: none;
  top: 0;
  transition: transform 300ms ease-in-out, background 300ms ease-in-out;
  width: 200%;
}
```
